# Generated by Django 6.0.6 on 2026-07-01 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAmenaza',
            fields=[
                ('id_amenaza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_amenaza', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amenaza',
                'verbose_name_plural': 'Catálogo de Amenazas',
                'db_table': 'Catalogo_Amenazas',
            },
        ),
        migrations.CreateModel(
            name='CatalogoISO',
            fields=[
                ('id_control', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('norma', models.CharField(max_length=100)),
                ('dominio', models.CharField(max_length=100)),
                ('titulo_control', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Control ISO',
                'verbose_name_plural': 'Catálogo ISO',
                'db_table': 'Catalogo_ISO',
            },
        ),
        migrations.CreateModel(
            name='CatalogoVulnerabilidad',
            fields=[
                ('id_vulnerabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vulnerabilidad', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Catálogo de Vulnerabilidades',
                'db_table': 'Catalogo_Vulnerabilidades',
            },
        ),
        migrations.CreateModel(
            name='ParamEstadoActivo',
            fields=[
                ('id_estado_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de Activo',
                'verbose_name_plural': 'Estados de Activos',
                'db_table': 'Param_Estados_Activo',
            },
        ),
        migrations.CreateModel(
            name='ParamTipoActivo',
            fields=[
                ('id_tipo_activo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ejemplo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activos',
                'db_table': 'Param_Tipos_Activo',
            },
        ),
        migrations.CreateModel(
            name='ParamTipoUbicacion',
            fields=[
                ('id_tipo_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Ubicación',
                'verbose_name_plural': 'Tipos de Ubicaciones',
                'db_table': 'Param_Tipos_Ubicacion',
            },
        ),
        migrations.CreateModel(
            name='ControlEmpresa',
            fields=[
                ('id_control_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_control', models.CharField(max_length=150)),
                ('naturaleza_valor', models.IntegerField()),
                ('ejecucion_valor', models.IntegerField()),
                ('documentacion_valor', models.IntegerField()),
                ('eficacia_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_iso_padre', models.ForeignKey(db_column='id_iso_padre', on_delete=django.db.models.deletion.RESTRICT, related_name='controles_empresa', to='api.catalogoiso')),
            ],
            options={
                'verbose_name': 'Control de Empresa',
                'verbose_name_plural': 'Controles de Empresa',
                'db_table': 'Controles_Empresa',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_activo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('sistema_involucrado', models.CharField(max_length=100)),
                ('sensibilidad', models.IntegerField(blank=True, null=True)),
                ('funcion_activo', models.CharField(blank=True, max_length=200, null=True)),
                ('area_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_administrative', models.CharField(blank=True, max_length=100, null=True)),
                ('confidencialidad', models.IntegerField()),
                ('integridad', models.IntegerField()),
                ('disponibilidad', models.IntegerField()),
                ('valor_final_max', models.IntegerField(blank=True, null=True)),
                ('nivel_impacto', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('id_propietario', models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.RESTRICT, related_name='activos_propietario', to=settings.AUTH_USER_MODEL)),
                ('id_estado_activo', models.ForeignKey(db_column='id_estado_activo', on_delete=django.db.models.deletion.RESTRICT, related_name='activos', to='api.paramestadoactivo')),
                ('id_tipo_activo', models.ForeignKey(db_column='id_tipo_activo', on_delete=django.db.models.deletion.RESTRICT, related_name='activos', to='api.paramtipoactivo')),
                ('id_tipo_ubicacion', models.ForeignKey(db_column='id_tipo_ubicacion', on_delete=django.db.models.deletion.RESTRICT, related_name='activos', to='api.paramtipoubicacion')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_riesgo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('amenaza_otro', models.CharField(blank=True, max_length=200, null=True)),
                ('vulnerabilidad_otro', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel_probabilidad', models.IntegerField()),
                ('nivel_vulnerabilidad', models.IntegerField()),
                ('score_inherente', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='api.activo')),
                ('id_amenaza', models.ForeignKey(blank=True, db_column='id_amenaza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos', to='api.catalogoamenaza')),
                ('id_vulnerabilidad_cat', models.ForeignKey(blank=True, db_column='id_vulnerabilidad_cat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos', to='api.catalogovulnerabilidad')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'db_table': 'Riesgos',
            },
        ),
        migrations.CreateModel(
            name='TratamientoRiesgo',
            fields=[
                ('id_treatment', models.AutoField(primary_key=True, serialize=False)),
                ('estrategia', models.CharField(max_length=50)),
                ('probabilidad_residual', models.IntegerField()),
                ('impacto_residual', models.IntegerField()),
                ('score_residual', models.IntegerField(blank=True, null=True)),
                ('nivel_residual', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_activo', models.BooleanField(default=True)),
                ('id_control_emp', models.ForeignKey(db_column='id_control_emp', on_delete=django.db.models.deletion.RESTRICT, related_name='tratamientos', to='api.controlempresa')),
                ('id_responsable', models.ForeignKey(db_column='id_responsable', on_delete=django.db.models.deletion.RESTRICT, related_name='tratamientos_responsable', to=settings.AUTH_USER_MODEL)),
                ('id_riesgo', models.ForeignKey(db_column='id_riesgo', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='api.riesgo')),
            ],
            options={
                'verbose_name': 'Tratamiento de Riesgo',
                'verbose_name_plural': 'Tratamientos de Riesgo',
                'db_table': 'Tratamiento_Riesgo',
            },
        ),
        migrations.CreateModel(
            name='HistorialTratamientoRiesgo',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('probabilidad_registrada', models.IntegerField()),
                ('impacto_registrado', models.IntegerField()),
                ('score_registrado', models.IntegerField(blank=True, null=True)),
                ('nivel_registrado', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion_cambio', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario_cambio', models.ForeignKey(db_column='id_usuario_cambio', on_delete=django.db.models.deletion.RESTRICT, related_name='historial_cambios', to=settings.AUTH_USER_MODEL)),
                ('id_riesgo', models.ForeignKey(db_column='id_riesgo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historial', to='api.riesgo')),
                ('id_treatment', models.ForeignKey(db_column='id_treatment', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historial', to='api.tratamientoriesgo')),
            ],
            options={
                'verbose_name': 'Historial de Tratamiento',
                'verbose_name_plural': 'Historial de Tratamientos',
                'db_table': 'Historial_Tratamiento_Riesgo',
            },
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['id_propietario'], name='IX_Activos_Propietario'),
        ),
        migrations.AddIndex(
            model_name='riesgo',
            index=models.Index(fields=['id_activo'], name='IX_Riesgos_Activo'),
        ),
        migrations.AddIndex(
            model_name='tratamientoriesgo',
            index=models.Index(fields=['id_riesgo'], name='IX_Tratamiento_Riesgo'),
        ),
        migrations.AddIndex(
            model_name='tratamientoriesgo',
            index=models.Index(fields=['id_responsable'], name='IX_Tratamiento_Responsable'),
        ),
        migrations.AddIndex(
            model_name='historialtratamientoriesgo',
            index=models.Index(fields=['fecha_cambio'], name='IX_Historial_Fecha'),
        ),
        migrations.AddIndex(
            model_name='historialtratamientoriesgo',
            index=models.Index(fields=['id_riesgo'], name='IX_Historial_Riesgo'),
        ),
    ]
